import DashboardShell from '@/components/DashboardShell';
import EmptyState from '@/components/EmptyState';
import SiteTable from '@/components/SiteTable';
import SiteTableSkeleton from '@/components/SkeletonTable';
import { useAuth } from '@/lib/auth';
import { fetcher } from '@/utils/fetcher';
import Head from 'next/head';
import React from 'react';
import useSWR from 'swr';

export default function Dashboard() {
    const auth = useAuth();
    const { data, error } = useSWR('/api/sites', fetcher);
    console.log(data);
    if (!data) {
        return (
            <DashboardShell>
                {' '}
                <SiteTableSkeleton />
            </DashboardShell>
        );
    }
    return (
        <>
            <Head>
                <title>Quick Feedback | Dashboard</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <DashboardShell>
                {data.sites.length > 0 ? (
                    <SiteTable sites={data.sites} />
                ) : (
                    <EmptyState />
                )}
            </DashboardShell>
        </>
    );
}
