import DashboardShell from '@/components/DashboardShell';
import EmptyState from '@/components/EmptyState';
import FeedbackTable from '@/components/FeedbackTable';
import SiteTable from '@/components/SiteTable';
import SiteTableSkeleton from '@/components/SkeletonTable';
import TableHeader from '@/components/TableHeader';
import { useAuth } from '@/lib/auth';
import { fetcher } from '@/utils/fetcher';
import Head from 'next/head';
import React from 'react';
import useSWR from 'swr';

export default function Feedback() {
    const auth = useAuth();
    const { data, error } = useSWR(
        auth.user ? ['/api/feedback', auth.user.token] : null,
        fetcher
    );
    console.log(data);
    if (!data) {
        return (
            <DashboardShell>
                <TableHeader label={'Feedback'} />
                <SiteTableSkeleton />
            </DashboardShell>
        );
    }
    return (
        <>
            <Head>
                <title>Quick Feedback | Dashboard</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <DashboardShell>
                <TableHeader label={'Feedback'} />
                {data.feedbacks.length > 0 ? (
                    <FeedbackTable feedbacks={data.feedbacks} />
                ) : (
                    <EmptyState />
                )}
            </DashboardShell>
        </>
    );
}
