import Head from 'next/head';
import Image from 'next/image';
import { useAuth } from '@/lib/auth';
import { LogoGithub } from '@chakra-icons/ionicons';
import { LogoGoogle } from '@chakra-icons/ionicons';
import {
    Button,
    Container,
    Flex,
    Heading,
    Stack,
    Text
} from '@chakra-ui/react';
import Link from 'next/link';

export default function Home() {
    const auth = useAuth();
    return (
        <Container>
            <Head>
                <title>Quick Feedback</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Flex
                as="main"
                direction="column"
                align={'center'}
                justify={'center'}
                minHeight="100vh"
            >
                <Heading textAlign={'center'}>Quick Feedback</Heading>
                {auth.user ? (
                    <Flex
                        gap={'4'}
                        direction={'column'}
                        align={'center'}
                        paddingTop={'10'}
                    >
                        <Flex align={'center'} justify={'center'}>
                            <Image
                                layout="intrinsic"
                                height={50}
                                width={50}
                                src={auth.user.image}
                                alt={`Image of ${auth.user.name}`}
                            />
                            <Text fontWeight={600}>{auth.user.name}</Text>
                        </Flex>
                        <Stack mt={8} gap={2}>
                            <Button>
                                <Link href="/dashboard">Dashboard</Link>
                            </Button>
                            <Button
                                minWidth="64"
                                onClick={(e) => auth.signout()}
                            >
                                Sign Out
                            </Button>
                        </Stack>
                    </Flex>
                ) : (
                    <Stack mt={8} gap={2}>
                        <Button
                            leftIcon={<LogoGithub />}
                            minWidth="64"
                            onClick={(e) => auth.signinWithGithub()}
                        >
                            Sign In with Github
                        </Button>
                        <Button
                            leftIcon={<LogoGoogle />}
                            minWidth="64"
                            onClick={(e) => auth.signinWithGoogle()}
                        >
                            Sign In with Google
                        </Button>
                    </Stack>
                )}
            </Flex>
        </Container>
    );
}
